### ISSUE TITLE
cf_api not match in deployment and template

### ISSUE THREAD

**Issue by sszwed** [cloudfoundry-community/docker-services-boshworkspace#28]
in deployment is cf_api_uri: https://github.com/cloudfoundry-community/docker-services-boshworkspace/blob/master/deployments/docker-aws-vpc.yml#L21
in templates is cf_api_url: https://github.com/cloudfoundry-community/docker-services-boshworkspace/blob/master/templates/docker-properties.yml#L2

**Comment by rkoster** [comment]
@sszwed Fixed in above commit, thanks for reporting
